
name: Build Maven Projet

on:
  push:
    branches: [ reproduce-5153 ]
  pull_request:
    branches: [ reproduce-5153 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Move JAR to root directory
      run: |
        mkdir -p package-jar
        find target -name "*.jar" -exec cp {} ./ \;
    
    - name: Configure Git
      run: |
        git config user.name "jvpreis"
        git config user.email "jvpreis@gmail.com"

    - name: Commit and push JAR to reproduce-5153 branch
      run: |
        git checkout -b reproduce-5153 || git checkout reproduce-5153
        git add *.jar
        git commit -m "Add generated JAR file to reproduce-5153 branch" || echo "No changes to commit"
        git push origin reproduce-5153

