- name: SonarCloud Quality Gate check
  id: sonarqube-quality-gate-check
  uses: sonarsource/sonarqube-quality-gate-action@master
  with:
    pollingTimeoutSec: 600
  env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
